### ISSUE TITLE
Wallet disappear from main window

### ISSUE THREAD

**Issue by emanuelelaface** [Overtorment/BlueWallet#11]
From fresh installation create a new wallet, then go to Settings, click on the menu icon on top left, it will appear the build version (mine is BlueWallet v.1.2.0 (build 25)), if I touch the build version it returns to the main window but the wallet disappears.

The wallet is still there because send and receive work correctly and if I close and reopen the app the wallet is again in the main window, but I do not think this is a correct behaviour.

I use an iPhone 6s with iOS 11.3.1.

**Comment by Overtorment** [comment]
Okay, you actually found a debugging shortcut :-) 
I'll just remove it.
