### ISSUE TITLE
Replace comma by decimal dot in create transaction inputs keyboard

### ISSUE THREAD

**Issue by monkjuice** [Overtorment/BlueWallet#16]
When trying to create a new transaction, as I try to input btc and fee inputs, a comma is shown in the keyboard instad of a decimal dot, so when I try to create the new transaction, an error is returned showing 

"new BigNumber() not a number: 0,05"

**Comment by Overtorment** [comment]
Can you post a screenshot?
This is a system keyboard for numeric inputs, my guess is your system settings for locale are such, that your delimiter for fractional numbers is comma instead of a dot.

Anyway, I'll fix it in next release (will make it accept and comma and dot equally)
