### ISSUE TITLE
Unable to broadcast transaction

### ISSUE THREAD

**Issue by monkjuice** [Overtorment/BlueWallet#17]
Hello,

 When I try to broadcast a transaction after succesfully creating the transaction hex, I'm unable to broadcast it, the "Broadcast" button is unresponsive.

EDIT: iOS version 11.3.1
EDIT 2: Ran test, and it returns OK

**Comment by Overtorment** [comment]
Fixed! 
SSL cert expired on pushtx endpoint. Renewed it.

TODO: use several independent endpoins for pushtx

**Comment by Overtorment** [comment]
several endpoins implemented in https://github.com/Overtorment/BlueWallet/projects/1#card-10453427
