### ISSUE TITLE
btczen API error, "min relay fee not met" - blockzypher failing to return Transactions

### ISSUE THREAD

**Issue by monkjuice** [Overtorment/BlueWallet#18]
When trying to broadcast a tx, placing 120sat/b as a fee, the error code -26, message: min relay fee not met is returned.

EDIT:  (i) SOMEHOW, the transaction was succesfully broadcasted (I tried broadcasting several times as I didn't understand the error), and this issue clearly belongs to the btczen API, as the error is that I do not have enough funds ATM.
(ii) I suggest adding a pre-loader and disabling the button when clicking on broadcast transaction, as I think, that was MY mistake in first place.
(iii) The real issue here, is that my "Transactions" view, is not updating, I still see my first input transaction recieved with 0 conf, and my only output transaction does not exist, is this a blockzypher integration error?

**Comment by Overtorment** [comment]
Clearly this screen needs some work.
And yes, Blockcypher has its own issues, sometimes "not seeing" unconfirmed transactions, thus 
returning outdated list of unspend outputs


Also, "min relay fee not met " is an error returned by BitcoinCore. Probably fee is not correctly calculated on BlueWallet side, but I cant reproduce that scenarion.

**Comment by monkjuice** [comment]
The problem is not on the satoshis per byte for sure, as I tried to copy the transaction hex and broadcasting it directly through btczen API using the URI, and using around 16000 sats as fee, and the problem persisted.
 If im not wrong, the fee amount is checked before checking the actual amount to spend in bitcoincore, and as it detects I have no funds to commit such fee, it returns this partially wrong error displaying that I do not have enough funds to pay the fee that I'm trying to pay.
