### ISSUE TITLE
Send/Receive works?

### ISSUE THREAD

**Issue by StanislavSergeev** [Overtorment/BlueWallet#2]
I clone this app, and run on my device.
But it seems that send/receive does not work.
And is this published to app store?

**Comment by StanislavSergeev** [comment]
Which api did you use for this project?
Is there any way to test without real bitcoin?

**Comment by Overtorment** [comment]
Blockcypher api.
Testnet not supported, but Ill add it to roadmap, seems like its a nice to have feature
