### ISSUE TITLE
HD wallet

### ISSUE THREAD

**Issue by Overtorment** [Overtorment/BlueWallet#23]
http://murch.one/wp-content/uploads/2016/11/erhardt2016coinselection.pdf

 BIP49:
m/49'/0'/a'/c/i

**Comment by Overtorment** [comment]
https://iancoleman.io/bip39/#english

**Comment by Overtorment** [comment]
https://github.com/bitcoinjs/bip39

**Comment by themotu** [comment]
What's still TODO for HD wallet?

**Comment by Overtorment** [comment]
@themotu basically done and released in v2.4.0
A couple of minor bugs I'm fixing and releasing ASAP

**Comment by Overtorment** [comment]
released in 2.4.1
