### ISSUE TITLE
Wallet does not work.

### ISSUE THREAD

**Issue by StanislavSergeev** [Overtorment/BlueWallet#4]
I sent small amout of bitcoin to Blue wallet.
Please check this transiaction.

> https://blockchain.info/tx/8b705de75c01b6db2461b8c73d42decc4c64a88a3c43fe14db3e13119f85a20c

It sent successfully to my Blue wallet, but my blue wallet is always empty. There won't any transactions display and any amount received.

![screenshot_20180502-172139](https://user-images.githubusercontent.com/36923678/39530342-1d1f2e78-4e6c-11e8-909b-538bda8b3a64.png)

This is my BlueWallet public address.

**Comment by Overtorment** [comment]
Can you try pressing Refresh button on Transactions screen..? Top right button

**Comment by Overtorment** [comment]
This is early beta, so for now, yes.
Ill fix this eventually.

**Comment by StanislavSergeev** [comment]
Yes, I am working on Android device.
So it is impossible to fix this?

**Comment by Overtorment** [comment]
It is possible, It just requires time to debug, and an android device, which I don’t have.

**Comment by StanislavSergeev** [comment]
Thanks for your help.
I will try to fix my self.

**Comment by StanislavSergeev** [comment]
Can I ask one more thing?
why 'metro-bunjdler+0.9.2.patch' is integrated in the project?
what does it do?
Thanks.

**Comment by Overtorment** [comment]
expo build scripts break something. Dont remember for sure, either Buffer or Crypto modules, so this patch is a workaround so expo build wont break some libraries
