### ISSUE TITLE
Receive work but Send does not work in iOS

### ISSUE THREAD

**Issue by StanislavSergeev** [Overtorment/BlueWallet#8]
https://blockchain.info/tx/3b0487ec13a1155f43d30de4abfa8e4c7abef0a6a2a9946819343cfd475e25c2

I sent few amount bitcoin from Blue wallet to my wallet.
And Transaction confirmed successfully but it never received.
The receiver address is the correct.
And coin was sent from blue wallet.

**Comment by Overtorment** [comment]
Looks like the problem on the side of second wallet? Tx visible on blockchain info and I assume all details are correct

**Comment by StanislavSergeev** [comment]
Maybe it will correct. Thanks.

**Comment by StanislavSergeev** [comment]
Hi, May I ask something?
At Request page, the public address is shown by Editable TextInput.
Why do you use TextInput? Why is it Editable?
Thanks.

**Comment by Overtorment** [comment]
I think its so the text inside input can be selected and copied. If the input is not editable it cant be selected.

**Comment by StanislavSergeev** [comment]
That's great idea. Now I am also developing bitcoin wallet, of course based on blue wallet.
Could we discuss more details to improve Blue Wallet?
Let me know if you agree.
My email: Stanislav.atos@gmail.com
Thanks.

**Comment by StanislavSergeev** [comment]
Perfect. I just checked iOS app on App Store.
Great Success!!!
I wanna to detach wallet from Expo. isn't there any other problem?
Because I have to use React native link. but it's not possible with Expokit so I decided to detach.
Okay?

**Comment by Overtorment** [comment]
Should work fine, but I haven't tried that

**Comment by StanislavSergeev** [comment]
Can I send bitcoin without fee in this app?

**Comment by Overtorment** [comment]
Yes theoretically if you put 0 in “fee” input, but these days nodes reject such transactions with error “min relay fee not met”

**Comment by StanislavSergeev** [comment]
Now I want to add new coin wallet to your project.
This coin was published 4 months ago and there won't any api libraries like bitcoin js.
It is developed by Qt and only qt desktop wallet is available now.
It will be great if you guide the general steps to develop this kind mobile wallet.
Thanks.

**Comment by Overtorment** [comment]
This might help, I wrote it couple of years ago https://habrahabr.ru/post/266779/

Your coin might have essentially the same cryptography, so maybe bitcoinjs will work (as it works for dogecoin/litecoin/dash/bcash), if not you need to find something close and rewrite it till it works.
And of course you'll need API to fetch/push data to your coin's network
